string:
  datasource:
    driver-class-name: org.mysql.Driver
    url: jdbc:mysql://localhost:3306/codemyth
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    slow-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.springframework: info
    org.hibernate: info